### ISSUE TITLE
Chrome

### ISSUE THREAD

**Issue by huseyinkarael** [DorsetDevStudio/Instagram_Bot#15]
Can I test with real chrome instead of test chrome?

**Comment by DorsetDevStudio** [comment]
Hi, it uses Real Chrome, the message at the top just highlights that it's being remote controlled.

If you check the Chrome version you will see it's identical to the one installed on your computer.

thanks

**Comment by huseyinkarael** [comment]
Are extensions in real Chrome not coming to other chrome?

**Comment by DorsetDevStudio** [comment]
@huseyinkarael 

by default all extensions are not added, I've found an article that explains how it may be possible to automatically load the users chrome profile which includes their extensions, I'll see if i can get this working.

https://seleniumjava.com/2016/05/22/start-the-chrome-browser-with-extensions/

Thanks

**Comment by DorsetDevStudio** [comment]
can you send me a link to the plugin, i may be able to package it up as an optional add on.

**Comment by huseyinkarael** [comment]
When I open the program I want to add my own chrome auto plugin for the computer. Is it possible?

**Comment by DorsetDevStudio** [comment]
@huseyinkarael 

I've just deployed an update, you can install your extensions and they will be there each time you launch the program. Hope this is what you're after.

When the bot is launched , open a new tab and use that tab to install extensions.

Thanks

**Comment by huseyinkarael** [comment]
How do I add an automatic plugin?

**Comment by huseyinkarael** [comment]
My requirement is to make a small project which get the .crx file and make an exe file of it. To just click on, it automatically add extension in google chrome extension. I want to do it in c# winform.

**Comment by pbh-stu** [comment]
Love to help, but it's not really in the scope of this project.

**Comment by huseyinkarael** [comment]
thanks.
