### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by huseyinkarael** [DorsetDevStudio/Instagram_Bot#9]
what is the error? 

![image](https://user-images.githubusercontent.com/39198208/40019703-e5c68d72-57b7-11e8-9d4c-bcefbe057e2b.png)

**Comment by DorsetDevStudio** [comment]
![image](https://user-images.githubusercontent.com/39198208/40019683-da497c02-57b7-11e8-94f0-d6420486640a.png)

**Comment by DorsetDevStudio** [comment]
Hi, please ensure you have dot net 4.7 installed.

![image](https://user-images.githubusercontent.com/39198208/40019769-186807ba-57b8-11e8-96dd-4d51c57e23e0.png)

**Comment by huseyinkarael** [comment]
programs does not comment.

**Comment by pbh-stu** [comment]
if you have the file c:/comments.txt please try deleting it and try again. If no file is present it will use the built in comments that I know do work.
